opt_in_rules:
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline

  - empty_count
  - explicit_init
  - extension_access_modifier

  - fatal_error_message
  - first_where
  - force_unwrapping

  - implicit_return

  - let_var_whitespace

  - multiline_parameters

  - nimble_operator - discuss
  - number_separator
  - overridden_super_call

  - prohibited_super_call

  - redundant_nil_coalescing

  - unneeded_parentheses_in_closure_argument

  - vertical_parameter_alignment_on_call

disabled_rules:
  - object_literal
  - trailing_whitespace
  - number_separator
  - private_over_fileprivate
excluded:
  - Carthage
  - Pods
  - Generated

line_length: 200

cyclomatic_complexity:
  ignores_case_statements: true

type_body_length:
  - 500 # warning
  - 700 # error

file_length:
  warning: 500
  error: 1200

function_parameter_count:
  error: 5

identifier_name:
  excluded:
    - id
    - ok
    - URL
    - x
    - y
    - z

warning_threshold: 2

custom_rules:
  uiwebview_disabled:
    included: ".*.swift"
    name: "UIWebView Usage Disabled"
    regex: 'UIWebView'
    message: "Do not use UIWebView. Use WKWebView Instead. https://developer.apple.com/reference/uikit/uiwebview"
    severity: error

  zero:
    name: "Short .zero"
    regex: '\(top: 0, left: 0, bottom: 0, right: 0\)'
    message: "Please use short init `.zero`."
    severity: error

  marks_style:
    name: "Marks"
    regex: '// MARK: -?[a-zA-Z0-9]'
    message: "Marks should follow the following structure: // MARK: - Comment."
    severity: warning

  unowned:
    name: "Unowned"
    regex: 'unowned'
    message: "Please use `weak` instead."
    severity: error

  continue_keyword:
    name: "Continue"
    regex: 'continue'
    message: "Don't use continue instruction"
    severity: error
    match_kinds: keyword
